language: python
python:
- '3.6'
install:
- make install TARGET=test
script:
- pip install python-coveralls
- scripts/embedmd -d README.md
- make coverage
after_success:
- coveralls
deploy:
  provider: pypi
  user: SwamyDev
  password:
    secure: i16zIULstpz4RK3j/cuFm+WohZkbOCVxoFZbfwgvoTqQHs0KyipUB8uaF+1tZ5RxOnfDLsuiMh7MncheMVmWK7PrYW+dkQd9tPgdeOW+/5a8y717OObiMyAHNZIPbsnWkURv94+9YF+o+5up3qwNPSpzR7LF6fA3eU3T50GWYPAvW5+twFBEhG0cXXd0SQyQKItvBrSXyebEoOUuC9A4VcGK9WLhTRRIsbkEhE6Lro3Utalff6V8yO9dfu+Cmq3Tg1TMnEHzoJYLVGq/8XaO8Xsibtlqhj/LkmT0XRmmKS9Ukpq+pbyO+gmErsLRhzrGs4d6S6wnYvDY8+mm6raabKcHIYM3eEaggIvilLcs//mCH/4h+uS5b0JZEMeiX2Q4rsR4+hI9mzxtkTB84JP4ovwCm15HA2HVMbSZ325kh7GSI4JoBS+vBk7mYjvx0NNTj02a9ONO0asmNZiyzif68OOtx5RKIy1nroXAJ/2B0jbXHli3ViO+SHQsF2oSWDvPbHv2IEeaWJ8UxO7SWTI/dCcgujdzXCfjzJzqMF1UksDygIk1c+3RhYxhhZ6ZgYPMBqwWABX5D5Q5kk6BCT5dtsH/clcgnb1+MZ7CIqZ0kl6v96taR3hsBW5gFmTTQ1orZ7i+PVni5RGG0pNZWrmokL8eSNNoUTiomEEQ9TdSJs0=
  on:
    tags: true
  distributions: sdist bdist_wheel
