language: python
python:
- '3.6'
install:
- make install TARGET=test
script:
- pip install python-coveralls
- scripts/embedmd -d README.md
- make coverage
after_success:
- coveralls
deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: xxuiRuoPwv7kIR2Vn6sXFCiwttnwqb1eAUDsyagLHXzUoepbezthZ2SQEMxoS52Z1kL34gTzznynbD/0UXJhQK+RIFzOoZwxS563iKc4EWbcjKQGkaFg7pEnE1Ewr6CU5f8L0RrBV7LP4ogdv/M4+a25qsRt4lLGFaw4WxQTU7K6JqkWpx/ZoBFAum9IXWVwbxR/fnW7aaD8LOSxyHaJcVy3PtZ8T67WZ1NYf2Efs8KUPYQXGxkA0yr2OzHazSAsgBMqzZL/WgxTL+M7lcQGXWp1CDC3XthDiW/uxReyqRARfqeHaR8E38VLFNcUadWvJ1qDK6TobdB6A4qYKxht64lBnv+sPHBQU4h+nECtC7d5cQ0qhLZx7/9kwAATSiOn6PUnV6wGkYHPLK4v+9Fr9mN0u3yyvRgqn4QY8hSQP81K/P/0Z9V6B4Lio7mGaVjYSdJOlAgsiAW3IlhKI0uLm8rmIZ+GdazVrpvD4SsfOtnCD6/vr/XM+V2sH13S/vZRFyO15RJDarYQIsZ1F523HZv/Sc2byz6IY/0P9IQEADjBKz3kO9f/L4xr4FWJ5oGqcRojX40amwDKm0afOjhorZ5wZSFssz1/utGsiCdcU4le0GIf70AXkjDlD4j4Czz17HkUdFWxn5NVi2vjNgmJIIifkcTdX1e0W5r2tQWADNs=
  on:
    tags: true
  distributions: sdist bdist_wheel
